In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
from random import choice
from numpy import array, dot , random
import numpy as np

In [ ]:
#MCNEURON for AND
w = random.rand(2)
w[1] = 1
w[0] = 1
train_daa = [
    (array([0,0]), 0),
        (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),

]

In [ ]:
step_function = lambda x: 0 if x<2 else 1

In [ ]:
for x, _ in train_daa:
    result = dot(x,w)
    
    print("{}: {} -> {}".format(x[:2], result, step_function(result)))

In [ ]:
#Rosenblatt neuron

step_function = lambda x: 0 if x < 50 else 1

train_data = [
    (array([0,0,1]), 1),
        (array([0,1,1]), 0),
    (array([1,0,1]), 0),
    (array([1,1,1]), 1),

]

w= random.rand(3)

b = .1  #bias term

errors = []
eta = 0.1  #learning rate
n = 10000

for i in range(n):
    x, expected = choice(train_data)
    
    #w = np.append(w,b)
    
    result = dot(w, x)
    
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error *x
    
    
for x, _ in train_data:
    result = dot(w, x)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))
    
