<a href="https://colab.research.google.com/github/misrapk/Deep-Learning-Course-YT/blob/main/02Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
t = tf.constant([[1.,2.,3.],
             [4.,5.,6.]])   #matrix
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
t.shape

TensorShape([2, 3])

In [ ]:
t.dtype

tf.float32

In [ ]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t@tf.transpose(t)  #@ is similar to tf.matmul()

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [ ]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

# tensors and Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([2.,5.,7.])
a

array([2., 5., 7.])

In [ ]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 5., 7.])>

In [ ]:
t.numpy()   #np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 25., 49.])>

In [ ]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

# Type Conversion

In [ ]:
#tensorflow does not perform any type conversion automatically.

try:
    tf.constant(2.0) + tf.constant(40)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [ ]:
#use tf.cast to convert
t2 = tf.constant(30)

tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=32.0>

# Variables

tf.tensors are immutable  ie. we can't change/update the values. hence we cant use regular tensors to implement weights in a neural network.

In [ ]:
v1 = tf.Variable([[1.,2.,4.],
             [5.,6,7]])

v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 4.],
       [5., 6., 7.]], dtype=float32)>

In [ ]:
v1.assign(2*v1)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  8.],
       [10., 12., 14.]], dtype=float32)>

In [ ]:
v1[0,1]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
v1[0,1].assign(22)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 22.,  8.],
       [10., 12., 14.]], dtype=float32)>

In [ ]:
v1[:,2].assign([23,112])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2.,  22.,  23.],
       [ 10.,  12., 112.]], dtype=float32)>

In [ ]:
v1.scatter_nd_add(indices=[[0,0], [1,2]], updates=[100,200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[102.,  22.,  23.],
       [ 10.,  12., 312.]], dtype=float32)>

In [ ]:
try:
    v1[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


# other data structures


In [ ]:
tf.constant("helloworld")

<tf.Tensor: shape=(), dtype=string, numpy=b'helloworld'>

In [ ]:
tf.constant("cafeé")

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe\xc3\xa9'>

In [ ]:
[ord(c) for c in "cafe"]

[99, 97, 102, 101]

### Ragged Tensor

2Dimensions -
    1. 1st Dimension --> Regular Dimension(uniform dimension)

   2.  2nd Dimension --> Ragged Dimension(dimensions whose slice may have different lengths)

In [ ]:
p = tf.constant(['Cafe', 'Coffee', 'caff~', '#342@'])
p

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'Cafe', b'Coffee', b'caff~', b'#342@'], dtype=object)>

In [ ]:
r = tf.strings.unicode_decode(p, 'UTF8')
r

<tf.RaggedTensor [[67, 97, 102, 101], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 126], [35, 51, 52, 50, 64]]>

In [ ]:
tf.strings.length(p)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 5], dtype=int32)>

In [ ]:
r[1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 67, 111, 102, 102, 101, 101], dtype=int32)>

In [ ]:
r[1:3]

<tf.RaggedTensor [[67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 126]]>

In [ ]:
r2 = tf.ragged.constant([[45,55], [], [33]])
tf.concat([r,r2], axis=0)

<tf.RaggedTensor [[67, 97, 102, 101], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 126], [35, 51, 52, 50, 64], [45, 55], [], [33]]>

In [ ]:
r.to_tensor()

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 67,  97, 102, 101,   0,   0],
       [ 67, 111, 102, 102, 101, 101],
       [ 99,  97, 102, 102, 126,   0],
       [ 35,  51,  52,  50,  64,   0]], dtype=int32)>

### Sparse Tensors

In [ ]:
s = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],
                values=[1.,2.,3.],
                dense_shape=[3,4])

s

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [ ]:
s2 = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],
                values=[1.,2.,3.],
                dense_shape=[12,12])

s2

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([12 12], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(s2)

<tf.Tensor: shape=(12, 12), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
s*42

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([ 42.  84. 126.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

In [ ]:
try:
    s + 42.0
except TypeError as ex:
    print(ex)

unsupported operand type(s) for +: 'SparseTensor' and 'float'


In [ ]:
s3= tf.constant([[10.,20.], [30.,40.], [50.,60.],[70.,80.]])
s3

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.],
       [70., 80.]], dtype=float32)>

In [ ]:
tf.sparse.sparse_dense_matmul(s,s3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 30.,  40.],
       [ 20.,  40.],
       [210., 240.]], dtype=float32)>

### Tensor Array

In [ ]:

array = tf.TensorArray(dtype=tf.float32, size=3,clear_after_read=False)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3., 10.]))
array = array.write(2, tf.constant([5., 7.]))
tensor1 = array.read(1)

In [ ]:
tensor1 = array.read(1)

In [ ]:
tensor1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [ ]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3., 10.],
       [ 5.,  7.]], dtype=float32)>

### sets

In [ ]:

a = tf.constant([[1, 5, 9]])
b = tf.constant([[5, 6, 9, 11]])

In [ ]:
u = tf.sets.union(a,b)
u

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]], shape=(5, 2), dtype=int64), values=tf.Tensor([ 1  5  6  9 11], shape=(5,), dtype=int32), dense_shape=tf.Tensor([1 5], shape=(2,), dtype=int64))

In [ ]:
t